version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -e .

      - run:
          name: Run tests
          command: pytest
          
workflows:
  version: 2
  test:
    jobs:
      - test

