version: 2.1

orbs:
  codecov: codecov/codecov@5

jobs:
  test:
    docker:
      - image: cimg/python:3.11  # or your actual Python version
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -e .
            pip install pytest pytest-cov

      - run:
          name: Run tests with coverage
          command: |
            pytest --cov=dame_ts --cov-report=xml

      - codecov/upload:
          file: coverage.xml
          token: $CODECOV_TOKEN  # Required for private repos

workflows:
  test-and-upload:
    jobs:
      - test
