version: 2.1

orbs:
  codecov: codecov/codecov@5

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -e .

      - run:
          name: Run tests and generate coverage report
          command: |
            pytest --cov=dame_ts --cov-report=xml

      - codecov/upload:  # Upload coverage report
          file: coverage.xml

workflows:
  version: 2
  test-and-upload:
    jobs:
      - test
